services:
  voter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automate-voting
    restart: unless-stopped
    volumes:
      - ./valid_cookies.txt:/app/valid_cookies.txt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
